version: "3.1"

services:
  db:
    image: mariadb:10.5.17
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: weather
      MYSQL_PASSWORD: weather
      MYSQL_DATABASE: weather
    volumes:
      - ./docker/db/mariadb/data:/var/lib/mysql
      - ./docker/db/mariadb/mariadb.cnf:/etc/mariadb/mariadb.cnf
    ports:
      - "3312:3306"

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/DockerFile
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
    working_dir: /app
    expose:
      - 9000
    volumes:
      - ./app:/app
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php.ini
    links:
      - db

  nginx:
    image: nginx:alpine
    working_dir: /app
    volumes:
      - ./app:/app
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8899:80"
    links:
      - php-fpm